language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - pip install cython
  - pip install pot
  - pip install pytest
  - pip install .
script: 
  - pytest -v
branches:
  only:
    - master