language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
install:
  - pip install cython
  - pip install pot
  - pip install .
script: 
  - python setup.py test -v
branches:
  only:
    - master