dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.7-dev"
install:
  - pip install -U scipy
  - pip install cython
  - pip install pot --no-binary pot
  - pip install pytest
  - pip install keras
  - pip install tensorflow
  - pip install scikit-learn
  - pip install .
script: 
  - pytest -v
branches:
  only:
    - master